# Generated by Django 3.2 on 2021-07-27 01:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('cola_id', models.AutoField(primary_key=True, serialize=False)),
                ('cola_name', models.CharField(choices=[('cola 1', 'cola 1'), ('cola 2', 'cola 2')], max_length=10)),
                ('cola_time', models.CharField(choices=[('2min', '2min'), ('3min', '3min')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('client_id', models.AutoField(primary_key=True, serialize=False)),
                ('client_name', models.CharField(max_length=100)),
                ('client_status', models.CharField(default='No Atendido', max_length=20)),
                ('id_cola', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tac.ticket')),
            ],
        ),
    ]
